---
title: Short Paper
author:
  - name: Alice Anonymous
    email: alice@example.com
    affiliation: Some Institute of Technology
  - name: Bob Security
    email: bob@example.com
    affiliation: Another University
abstract: |
  This is the abstract.

  It consists of two paragraphs.
bibliography: sigproc.bib
csl: acm-sig-proceedings.csl
output: rticles::acm_article
---

# Abstract

# Introduction 

The project is based on VAST project 2021 about a fictional incident in Kronos. The fictional company, GASTech, a Tethys-based oil company has been operating a site in Kronos and had a celebration of IPO in 2014 Jan. The company had developed a strong relationship and cooperation with Kronos government. However, it received  backlash for its being unsuccessful in demonstrating environmental stewardship. 

A significant opposing activist group, named Protectors of Kronos, was established in 1997. The grassroot organization aimed to protest against water pollution that was suspected to be highly related to GASTech site in Kronos. In the early years of POK led by the founders, the organization planned several peaceful events and the sharp turn happened when the successor, Elian Karel, took the lead of the organization. The protests and other planned events became more violent, especially after Tiseke River caught fire in 2005 and the leader, Karel's death in 2009. The objective of the organization extends to protest against the government's corruption. It was also classified as violent and terrorist group in the recent years by the local government.

The incident happened on Jan 21 2014 during the celebration event of GASTech's IPO. Several employees were reported missing. POK was suspected to be responsible for the kidnap event. 


# Objective

In this project, we take the stand of analysts and use visual analytic tools to gain deep understanding of the event, employee relationship, employee lifestyle and transaction behaviours, and microblog reaction during the event. There are 3 mini challenges released in the VAST challenge. The group has attempted all challenges but the paper will focus on analysing the employees in GASTech.

+ 

# Method and approach

# Analysis

## MC1 - Inspect employee network to find suspected people

## MC2 - Inspect transaction and moving route of the suspected

## MC3 - 

# Conclusion

# Future study

# References

---
references:
- id: meier2012
  title: Professinal Android 4 Application Development
  author: 
  - family: Meier
    given: Reto
  type: book
  publisher: John Wiley & Sons, Inc.
  issued:
    year: 2012
    month: 5
- id: fenner2012a
  title: One-click science marketing
  author:
  - family: Fenner
    given: Martin
  container-title: Nature Materials
  volume: 11
  URL: 'https://doi.org/10.1038/nmat3283'
  DOI: 10.1038/nmat3283
  issue: 4
  publisher: Nature Publishing Group
  page: 261-263
  type: article-journal
  issued:
    year: 2012
    month: 3
...

